import type { Config } from "tailwindcss";

export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./ui/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        bo: {
          bg: "var(--bo-bg)",
          shell: "var(--bo-shell)",
          surface: "var(--bo-surface)",
          "surface-2": "var(--bo-surface-2)",
          "surface-3": "var(--bo-surface-3)",
          sidebar: "var(--bo-sidebar)",
          border: "var(--bo-border)",
          "border-2": "var(--bo-border-2)",
          text: "var(--bo-text)",
          muted: "var(--bo-muted)",
          faint: "var(--bo-faint)",
          accent: "var(--bo-accent)",
          "accent-2": "var(--bo-accent-2)",
          "accent-3": "var(--bo-accent-3)",
          success: "var(--bo-color-success)",
          warning: "var(--bo-color-warning)",
          danger: "var(--bo-color-danger)",
          "color-error": "var(--bo-color-danger)",
          info: "var(--bo-color-info)",
          "bg-selected": "var(--bo-bg-selected)",
          "surface-hover": "var(--bo-surface-hover)",
          primary: "var(--bo-primary)",
          "primary-rgb": "var(--bo-primary-rgb)",
          "primary-alpha": "var(--bo-primary-alpha)",
          "primary-hover": "var(--bo-primary-hover)",
          "primary-fg": "var(--bo-primary-fg)",
          fg: "var(--bo-fg)",
          "fg-inverted": "var(--bo-fg-inverted)",
          "bg-secondary": "var(--bo-bg-secondary)",
          "bg-subtle": "var(--bo-bg-subtle)",
          "bg-hover": "var(--bo-bg-hover)",
          "bg-muted": "var(--bo-bg-muted)",
          "bg-selected-hover": "var(--bo-bg-selected-hover)",
          "bg-primary": "var(--bo-bg-primary)",
          "surface-1": "var(--bo-surface-1)",
          "text-primary": "var(--bo-text-primary)",
          "text-secondary": "var(--bo-text-secondary)",
          "text-muted": "var(--bo-text-muted)",
          "color-primary": "var(--bo-color-primary)",
          "color-muted": "var(--bo-color-muted)",
          pending: "var(--bo-pending)",
          "success-bg": "var(--bo-success-bg)",
          "warning-bg": "var(--bo-warning-bg)",
          "warning-fg": "var(--bo-warning-fg)",
          "muted-bg": "var(--bo-muted-bg)",
          "card-bg": "var(--bo-card-bg)",
          "bg-2": "var(--bo-bg-2)",
          "bg-elevated": "var(--bo-bg-elevated)",
          "shadow-lg": "var(--bo-shadow-lg)",
          "font-mono": "var(--bo-font-mono)",
          "accent-alpha": "var(--bo-accent-alpha)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "bo-lg": "18px",
        "bo-md": "14px",
        "bo-sm": "12px",
        "bo-full": "9999px",
      },
      spacing: {
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "24px",
        "6": "32px",
        "8": "48px",
        "bo-1": "4px",
        "bo-2": "8px",
        "bo-3": "12px",
        "bo-4": "16px",
        "bo-5": "24px",
        "bo-6": "32px",
        "bo-8": "48px",
      },
      fontSize: {
        "xs": "10px",
        "sm": "12px",
        "base": "14px",
        "lg": "16px",
        "xl": "20px",
        "2xl": "24px",
        "3xl": "32px",
        "bo-xs": "10px",
        "bo-sm": "12px",
        "bo-base": "14px",
        "bo-lg": "16px",
        "bo-xl": "20px",
        "bo-2xl": "24px",
        "bo-3xl": "32px",
      },
      fontWeight: {
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        "bo-normal": "400",
        "bo-medium": "500",
        "bo-semibold": "600",
        "bo-bold": "700",
      },
      lineHeight: {
        tight: "1.25",
        normal: "1.4",
        relaxed: "1.6",
        "bo-tight": "1.25",
        "bo-normal": "1.4",
        "bo-relaxed": "1.6",
      },
      boxShadow: {
        "soft": "0 10px 26px rgba(0, 0, 0, 0.36)",
        "elevated": "0 18px 52px rgba(0, 0, 0, 0.55)",
        "bo": "0 18px 52px rgba(0, 0, 0, 0.55)",
        "bo-soft": "0 10px 26px rgba(0, 0, 0, 0.36)",
      },
      transitionDuration: {
        "fast": "120ms",
        "base": "150ms",
        "slow": "300ms",
        "bo-fast": "120ms",
        "bo-base": "150ms",
        "bo-slow": "300ms",
      },
      transitionTimingFunction: {
        "bo": "ease",
        "bo-out": "ease-out",
        "bo-in-out": "ease-in-out",
      },
      width: {
        "bo-sidebar": "78px",
      },
      height: {
        "bo-navBtn": "44px",
        "bo-actionBtn": "36px",
      },
      maxHeight: {
        "bo-48": "192px",
        "bo-60": "240px",
        "bo-72": "288px",
      },
      maxWidth: {
        "bo-full": "100%",
      },
      cursor: {
        "bo-move": "move",
        "bo-pointer": "pointer",
        "bo-not-allowed": "not-allowed",
      },
      zIndex: {
        "bo-10": "10",
        "bo-20": "20",
        "bo-50": "50",
      },
      animation: {
        "bo-pulse": "bo-pulse 1.5s ease-in-out infinite",
      },
      keyframes: {
        "bo-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
      },
      backgroundImage: {
        "bo-body": "var(--bo-body-bg)",
      },
      padding: {
        "bo-1": "var(--bo-space-1)",
        "bo-2": "var(--bo-space-2)",
        "bo-3": "var(--bo-space-3)",
        "bo-4": "var(--bo-space-4)",
        "bo-5": "var(--bo-space-5)",
        "bo-6": "var(--bo-space-6)",
      },
      margin: {
        "bo-1": "var(--bo-space-1)",
        "bo-2": "var(--bo-space-2)",
        "bo-3": "var(--bo-space-3)",
        "bo-4": "var(--bo-space-4)",
        "bo-5": "var(--bo-space-5)",
        "bo-6": "var(--bo-space-6)",
        "bo-8": "var(--bo-space-8)",
        "bo-mt-1": "var(--bo-space-1)",
        "bo-mt-2": "var(--bo-space-2)",
        "bo-mt-3": "var(--bo-space-3)",
        "bo-mt-4": "var(--bo-space-4)",
        "bo-mt-5": "var(--bo-space-5)",
        "bo-mt-6": "var(--bo-space-6)",
        "bo-mt-8": "var(--bo-space-8)",
        "bo-mb-1": "var(--bo-space-1)",
        "bo-mb-2": "var(--bo-space-2)",
        "bo-mb-3": "var(--bo-space-3)",
        "bo-mb-4": "var(--bo-space-4)",
        "bo-mb-5": "var(--bo-space-5)",
        "bo-mb-6": "var(--bo-space-6)",
        "bo-mb-8": "var(--bo-space-8)",
      },
      fontFamily: {
        "bo": "var(--bo-font)",
        "bo-serif": "var(--bo-font-serif)",
        "bo-mono": "var(--bo-font-mono)",
      },
      borderColor: {
        "bo-border": "var(--bo-border)",
        "bo-border-2": "var(--bo-border-2)",
        "bo-color-success": "var(--bo-color-success)",
        "bo-color-warning": "var(--bo-color-warning)",
        "bo-color-danger": "var(--bo-color-danger)",
        "bo-color-info": "var(--bo-color-info)",
        "bo-btn--primary": "color-mix(in srgb, var(--bo-accent) 16%, transparent)",
        "bo-btn--ghost": "transparent",
        "bo-btn--secondary": "var(--bo-surface-3)",
        "bo-btn--outline": "transparent",
        "bo-btn--danger": "color-mix(in srgb, var(--bo-color-danger) 16%, transparent)",
        "bo-btn--warning": "color-mix(in srgb, var(--bo-color-warning) 16%, transparent)",
        "bo-btn--success": "color-mix(in srgb, var(--bo-color-success) 16%, transparent)",
      },
      textColor: {
        "bo-text": "var(--bo-text)",
        "bo-muted": "var(--bo-muted)",
        "bo-faint": "var(--bo-faint)",
        "bo-accent": "var(--bo-accent)",
        "bo-success": "var(--bo-text-success)",
        "bo-warning": "var(--bo-text-warning)",
        "bo-danger": "var(--bo-text-danger)",
        "bo-info": "var(--bo-text-info)",
        "bo-color-success": "var(--bo-color-success)",
        "bo-color-warning": "var(--bo-color-warning)",
        "bo-color-danger": "var(--bo-color-danger)",
        "bo-color-info": "var(--bo-color-info)",
      },
      position: {
        "bo-relative": "relative",
        "bo-absolute": "absolute",
        "bo-fixed": "fixed",
        "bo-sticky": "sticky",
      },
      inset: {
        "bo-0": "0",
      },
      whitespace: {
        "bo-pre": "pre-line",
      },
      minWidth: {
        "bo-0": "0",
      },
      display: {
        "bo-flex": "flex",
        "bo-inline-flex": "inline-flex",
        "bo-grid": "grid",
        "bo-block": "block",
        "bo-inline-block": "inline-block",
        "bo-hidden": "none",
      },
      flexDirection: {
        "bo-flex-col": "column",
        "bo-flex-row": "row",
      },
      alignItems: {
        "bo-items-center": "center",
        "bo-items-start": "flex-start",
        "bo-items-end": "flex-end",
      },
      justifyContent: {
        "bo-justify-between": "space-between",
        "bo-justify-center": "center",
        "bo-justify-end": "flex-end",
      },
      gap: {
        "bo-gap-1": "var(--bo-space-1)",
        "bo-gap-2": "var(--bo-space-2)",
        "bo-gap-3": "var(--bo-space-3)",
        "bo-gap-4": "var(--bo-space-4)",
        "bo-gap-5": "var(--bo-space-5)",
        "bo-gap-6": "var(--bo-space-6)",
      },
      flex: {
        "bo-1": "1 1 0%",
        "bo-auto": "1 1 auto",
        "bo-initial": "0 1 auto",
        "bo-none": "none",
      },
      flexGrow: {
        "bo-0": "0",
        "bo-1": "1",
      },
      flexShrink: {
        "bo-0": "0",
        "bo-1": "1",
      },
      backgroundColor: {
        "bo-bg": "var(--bo-bg)",
        "bo-surface": "var(--bo-surface)",
        "bo-surface-2": "var(--bo-surface-2)",
        "bo-surface-3": "var(--bo-surface-3)",
        "bo-success": "var(--bo-color-success)",
        "bo-warning": "var(--bo-color-warning)",
        "bo-danger": "var(--bo-color-danger)",
        "bo-info": "var(--bo-color-info)",
        "bo-color-success": "var(--bo-color-success)",
        "bo-color-warning": "var(--bo-color-warning)",
        "bo-color-danger": "var(--bo-color-danger)",
        "bo-color-info": "var(--bo-color-info)",
        "bo-btn--primary": "color-mix(in srgb, var(--bo-accent) 16%, transparent)",
        "bo-btn--ghost": "transparent",
        "bo-btn--secondary": "var(--bo-surface-3)",
        "bo-btn--outline": "transparent",
        "bo-btn--danger": "color-mix(in srgb, var(--bo-color-danger) 16%, transparent)",
        "bo-btn--warning": "color-mix(in srgb, var(--bo-color-warning) 16%, transparent)",
        "bo-btn--success": "color-mix(in srgb, var(--bo-color-success) 16%, transparent)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
} satisfies Config;
