import React, { useState } from "react";
import type { LabourCostReport as Report } from "../../../../../api/types";

type Props={report:Report|null;loading:boolean;onRangeChange:(from:string,to:string)=>void};
const money=new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"});
export function LabourCostReport({report,loading,onRangeChange}:Props){
  const now=new Date(),monthFrom=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10),today=now.toISOString().slice(0,10);
  const [from,setFrom]=useState(report?.from||monthFrom),[to,setTo]=useState(report?.to||today);
  return <section className="grid gap-4 rounded-xl border border-[var(--bo-border)] bg-[var(--bo-surface)] p-4" data-ui="labour-report"><div className="flex flex-wrap items-end justify-between gap-3" data-ui="labour-report-header"><div data-ui="labour-report-heading"><h2 className="font-semibold" data-ui="labour-report-title">Coste laboral por fichajes</h2><p className="text-sm text-[var(--bo-muted)]" data-ui="labour-report-subtitle">Horas reales × coste empresa vigente cada día.</p></div><div className="flex flex-wrap items-end gap-2" data-ui="labour-report-range"><label className="grid gap-1 text-xs" data-ui="labour-report-from-label">Desde<input className="bo-input" type="date" value={from} onChange={event=>setFrom(event.target.value)} data-ui="labour-report-from" /></label><label className="grid gap-1 text-xs" data-ui="labour-report-to-label">Hasta<input className="bo-input" type="date" value={to} onChange={event=>setTo(event.target.value)} data-ui="labour-report-to" /></label><button className="bo-btn bo-btn--ghost" type="button" disabled={loading||!from||!to} onClick={()=>onRangeChange(from,to)} data-ui="labour-report-load">{loading?"Calculando...":"Calcular"}</button></div></div>{report?<><div className="grid gap-3 sm:grid-cols-2" data-ui="labour-report-summary"><div className="bo-kv" data-ui="labour-report-hours"><span className="bo-kvLabel" data-ui="labour-report-hours-label">Horas</span><strong className="bo-kvValue" data-ui="labour-report-hours-value">{(report.totalMinutes/60).toFixed(2).replace(".",",")} h</strong></div><div className="bo-kv" data-ui="labour-report-cost"><span className="bo-kvLabel" data-ui="labour-report-cost-label">Coste</span><strong className="bo-kvValue" data-ui="labour-report-cost-value">{money.format(report.totalCost)}</strong></div></div><div className="grid gap-2" data-ui="labour-report-members">{report.members.map(item=><div className="flex justify-between rounded-lg border border-[var(--bo-border)] p-3 text-sm" key={item.memberId} data-ui="labour-report-member"><span data-ui="labour-report-member-name">{item.name}{item.missingCompensation?" · salario pendiente":""}</span><strong data-ui="labour-report-member-cost">{(item.minutesWorked/60).toFixed(2).replace(".",",")} h · {money.format(item.cost)}</strong></div>)}</div>{report.missingCompensationMembers.length?<p className="text-sm text-[var(--bo-text-warning)]" role="alert" data-ui="labour-report-missing">Falta salario: {report.missingCompensationMembers.join(", ")}</p>:null}</>:<p className="text-sm text-[var(--bo-muted)]" data-ui="labour-report-empty">Carga periodo para calcular coste real.</p>}</section>;
}
