import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ClipboardCheck, Minus, Plus, Search } from "lucide-react";
import { navigate } from "vike/client/router";

import { Button } from "../../../../ui/actions/Button";
import { EmptyState } from "../../../../ui/feedback/EmptyState";
import { InlineAlert } from "../../../../ui/feedback/InlineAlert";
import { LoadingSpinner } from "../../../../ui/feedback/LoadingSpinner";

// Mobile-first recuento rápido (/app/stock/count): warehouse picker → open
// count sheet → big steppers per tracked item → confirm → close. Quantities
// are entered in the item's default display unit; the backend multiplies by
// factorToBase and applies the delta against stock_levels. Only touched lines
// are sent on close; an idempotency key generated when the sheet opens makes a
// retry after a flaky connection safe.

type Warehouse = { id: number; name: string; type: string; isDefault: boolean; isActive: boolean };
type CountLine = {
  itemId: number;
  name: string;
  expectedQuantityBase: number;
  observedQuantityBase: number | null;
  enteredQuantity: number | null;
  unitId: number;
  unitLabel: string;
  factorToBase: number;
};
type CountSheet = { id: number; warehouseId: number; warehouseName: string; status: string; lines: CountLine[] };
type Applied = { counted: number; changed: number; warehouseName: string };

const EPSILON = 1e-9;

class QcError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.status = status;
  }
}

async function qcRequest<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/admin/stock${path}`, {
    ...init,
    credentials: "include",
    headers: init?.body ? { "Content-Type": "application/json" } : undefined,
  });
  const body = await response.json().catch(() => ({}));
  if (!response.ok || body.success === false) throw new QcError(body.message || "Error de recuento", response.status);
  return body as T;
}

function parseQty(raw: string): number | null {
  const trimmed = raw.trim().replace(",", ".");
  if (trimmed === "") return null;
  const parsed = Number(trimmed);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : null;
}

function fmtQty(value: number): string {
  return String(Math.round(value * 1000) / 1000);
}

function deltaClass(qty: number, expected: number): string {
  const diff = qty - expected;
  if (Math.abs(diff) < EPSILON) return "bo-qcDelta--eq";
  return diff < 0 ? "bo-qcDelta--down" : "bo-qcDelta--up";
}

function deltaText(qty: number, expected: number): string {
  const diff = qty - expected;
  if (Math.abs(diff) < EPSILON) return "Coincide";
  return diff < 0 ? fmtQty(diff) : `+${fmtQty(diff)}`;
}

function expectedDisplay(line: CountLine): number {
  return line.factorToBase > 0 ? line.expectedQuantityBase / line.factorToBase : line.expectedQuantityBase;
}

export function QuickCount() {
  const [phase, setPhase] = useState<"pick" | "count" | "review" | "done">("pick");
  const [warehouses, setWarehouses] = useState<Warehouse[] | null>(null);
  const [warehouseId, setWarehouseId] = useState<number | null>(null);
  const [sheet, setSheet] = useState<CountSheet | null>(null);
  const [entries, setEntries] = useState<Record<number, string>>({});
  const [search, setSearch] = useState("");
  const [starting, setStarting] = useState(false);
  const [closing, setClosing] = useState(false);
  const [error, setError] = useState("");
  const [applied, setApplied] = useState<Applied | null>(null);
  // One key per sheet lifecycle; regenerated by reset() for the next count.
  const idempotencyKey = useRef<string>("");
  // Sheet created but not yet loaded (GET failed mid-start): reused on retry so
  // "Iniciar recuento" doesn't orphan a second OPEN sheet in the warehouse.
  const pendingSheet = useRef<{ id: number; warehouseId: number } | null>(null);

  useEffect(() => {
    let cancelled = false;
    qcRequest<{ warehouses: Warehouse[] }>("/warehouses")
      .then((body) => {
        if (cancelled) return;
        const active = (body.warehouses || []).filter((warehouse) => warehouse.isActive !== false);
        setWarehouses(active);
        const def = active.find((warehouse) => warehouse.isDefault) || active[0];
        if (def) setWarehouseId(def.id);
      })
      .catch((reason) => {
        if (!cancelled) setError(reason instanceof Error ? reason.message : "No se pudieron cargar los almacenes");
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const reset = useCallback(() => {
    setSheet(null);
    setEntries({});
    setSearch("");
    setError("");
    setApplied(null);
    pendingSheet.current = null;
    idempotencyKey.current = typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-qc`;
    setPhase("pick");
  }, []);

  useEffect(() => {
    idempotencyKey.current = typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-qc`;
  }, []);

  const start = useCallback(async () => {
    if (!warehouseId) return;
    setStarting(true);
    setError("");
    try {
      let sheetId = pendingSheet.current?.id;
      if (!sheetId || pendingSheet.current?.warehouseId !== warehouseId) {
        const created = await qcRequest<{ id: number }>("/counts", {
          method: "POST",
          body: JSON.stringify({ warehouseId }),
        });
        sheetId = created.id;
        pendingSheet.current = { id: sheetId, warehouseId };
      }
      const loaded = await qcRequest<CountSheet>(`/counts/${sheetId}`);
      pendingSheet.current = null;
      if (loaded.status !== "OPEN") {
        setError("Ese recuento ya está cerrado. Inicia uno nuevo.");
        setPhase("pick");
        return;
      }
      setSheet(loaded);
      setEntries({});
      setSearch("");
      setPhase("count");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "No se pudo abrir el recuento");
    } finally {
      setStarting(false);
    }
  }, [warehouseId]);

  const visibleLines = useMemo(() => {
    if (!sheet) return [];
    const query = search.trim().toLowerCase();
    if (!query) return sheet.lines;
    return sheet.lines.filter((line) => line.name.toLowerCase().includes(query));
  }, [sheet, search]);

  const touchedLines = useMemo(() => {
    if (!sheet) return [];
    return sheet.lines.filter((line) => parseQty(entries[line.itemId] ?? "") !== null);
  }, [sheet, entries]);

  const bump = useCallback((itemId: number, delta: number) => {
    setEntries((current) => {
      const base = parseQty(current[itemId] ?? "") ?? 0;
      return { ...current, [itemId]: fmtQty(Math.max(0, base + delta)) };
    });
  }, []);

  const sanitize = useCallback((itemId: number) => {
    setEntries((current) => {
      const raw = current[itemId];
      if (raw === undefined) return current;
      if (raw.trim() === "") {
        const next = { ...current };
        delete next[itemId];
        return next;
      }
      if (parseQty(raw) === null) return { ...current, [itemId]: "0" };
      return current;
    });
  }, []);

  const applyClose = useCallback(async () => {
    if (!sheet) return;
    const lines = touchedLines.map((line) => ({
      itemId: line.itemId,
      quantity: parseQty(entries[line.itemId] ?? "") as number,
      unitId: line.unitId,
    }));
    if (lines.length === 0) return;
    setClosing(true);
    setError("");
    try {
      await qcRequest(`/counts/${sheet.id}/close`, {
        method: "POST",
        body: JSON.stringify({ lines, idempotencyKey: idempotencyKey.current }),
      });
      const changed = lines.filter((entry) => {
        const line = sheet.lines.find((candidate) => candidate.itemId === entry.itemId);
        if (!line) return false;
        return Math.abs(entry.quantity - expectedDisplay(line)) >= EPSILON;
      }).length;
      setApplied({ counted: lines.length, changed, warehouseName: sheet.warehouseName });
      setPhase("done");
    } catch (reason) {
      const status = reason instanceof QcError ? reason.status : 0;
      if (status === 409) {
        setError("El recuento ya se cerró desde otro dispositivo.");
        setSheet(null);
        setEntries({});
        pendingSheet.current = null;
        setPhase("pick");
      } else {
        setError(reason instanceof Error ? reason.message : "No se pudo cerrar el recuento");
        setPhase("count");
      }
    } finally {
      setClosing(false);
    }
  }, [sheet, touchedLines, entries]);

  const renderPicker = () => (
    <div className="bo-qcCard" data-ui="qc-picker">
      <h1 className="bo-qcTitle" data-ui="qc-title">Recuento rápido</h1>
      <p className="bo-qcMuted" data-ui="qc-hint">
        Elige el almacén y cuenta artículo por artículo. Al cerrar, el stock se ajusta a lo contado.
      </p>
      {warehouses === null ? (
        <LoadingSpinner centered size="sm" label="Cargando almacenes…" />
      ) : warehouses.length === 0 ? (
        <EmptyState title="Sin almacenes" description="Crea un almacén en Stock antes de contar." data-ui="qc-empty-warehouses" />
      ) : (
        <div className="bo-qcWhList" role="group" aria-label="Almacén a contar" data-ui="qc-warehouses">
          {warehouses.map((warehouse) => (
            <button
              type="button"
              key={warehouse.id}
              className="bo-qcWh"
              aria-pressed={warehouseId === warehouse.id}
              onClick={() => setWarehouseId(warehouse.id)}
              data-ui={`qc-warehouse-${warehouse.id}`}
              data-testid={`qc-warehouse-${warehouse.id}`}
            >
              <span data-ui={`qc-warehouse-name-${warehouse.id}`}>{warehouse.name}</span>
              <span className="bo-qcWhType" data-ui={`qc-warehouse-type-${warehouse.id}`}>
                {warehouse.isDefault ? "Principal" : warehouse.type}
              </span>
            </button>
          ))}
        </div>
      )}
      {error ? <InlineAlert kind="error" title={error} /> : null}
      <Button
        variant="primary"
        disabled={!warehouseId || starting || warehouses === null || warehouses.length === 0}
        onClick={() => void start()}
        data-ui="qc-start"
        data-testid="qc-start"
      >
        {starting ? "Abriendo…" : "Iniciar recuento"}
      </Button>
    </div>
  );

  const renderCount = () => {
    if (!sheet) return null;
    return (
      <>
        <div className="bo-qcHead" data-ui="qc-counthead">
          <h1 className="bo-qcTitle" data-ui="qc-count-title">{sheet.warehouseName}</h1>
          <span className="bo-qcMuted" data-ui="qc-count-progress">
            {touchedLines.length}/{sheet.lines.length} contados
          </span>
        </div>
        <div className="bo-qcSearchWrap" data-ui="qc-searchwrap">
          <Search size={16} className="bo-qcSearchIco" aria-hidden="true" />
          <input
            className="bo-input bo-qcSearch"
            placeholder="Buscar artículo…"
            value={search}
            aria-label="Buscar artículo"
            onChange={(event) => setSearch(event.target.value)}
            data-ui="qc-search"
            data-testid="qc-search"
          />
        </div>
        {error ? <InlineAlert kind="error" title={error} /> : null}
        {sheet.lines.length === 0 ? (
          <EmptyState
            title="Nada que contar"
            description="Este almacén no tiene artículos trazables."
            data-ui="qc-empty-lines"
          />
        ) : visibleLines.length === 0 ? (
          <p className="bo-qcMuted" data-ui="qc-nosearch">Sin resultados para «{search}».</p>
        ) : (
          <div className="bo-qcLines" data-ui="qc-lines">
            {visibleLines.map((line) => {
              const raw = entries[line.itemId] ?? "";
              const qty = parseQty(raw);
              const expected = expectedDisplay(line);
              const touched = qty !== null;
              return (
                <div className="bo-qcLine" key={line.itemId} data-ui={`qc-line-${line.itemId}`}>
                  <div className="bo-qcLineHead" data-ui={`qc-line-head-${line.itemId}`}>
                    <span className="bo-qcLineName" data-ui={`qc-line-name-${line.itemId}`}>{line.name}</span>
                    <span className="bo-qcLineExpected" data-ui={`qc-line-expected-${line.itemId}`}>
                      Esperado {fmtQty(expected)} {line.unitLabel}
                    </span>
                  </div>
                  <div className="bo-qcStepper" data-ui={`qc-line-stepper-${line.itemId}`}>
                    <button
                      type="button"
                      className="bo-qcStepBtn"
                      aria-label={`Quitar uno a ${line.name}`}
                      onClick={() => bump(line.itemId, -1)}
                      data-ui={`qc-minus-${line.itemId}`}
                      data-testid={`qc-minus-${line.itemId}`}
                    >
                      <Minus size={18} aria-hidden="true" />
                    </button>
                    <input
                      className={`bo-qcInput${touched ? " is-touched" : ""}`}
                      inputMode="decimal"
                      autoComplete="off"
                      value={raw}
                      placeholder="—"
                      aria-label={`Cantidad de ${line.name} en ${line.unitLabel}`}
                      onChange={(event) => {
                        const value = event.target.value;
                        setEntries((current) => ({ ...current, [line.itemId]: value }));
                      }}
                      onBlur={() => sanitize(line.itemId)}
                      data-ui={`qc-input-${line.itemId}`}
                      data-testid={`qc-input-${line.itemId}`}
                    />
                    <button
                      type="button"
                      className="bo-qcStepBtn"
                      aria-label={`Añadir uno a ${line.name}`}
                      onClick={() => bump(line.itemId, 1)}
                      data-ui={`qc-plus-${line.itemId}`}
                      data-testid={`qc-plus-${line.itemId}`}
                    >
                      <Plus size={18} aria-hidden="true" />
                    </button>
                  </div>
                  {touched ? (
                    <span className={`bo-qcDelta ${deltaClass(qty as number, expected)}`} data-ui={`qc-delta-${line.itemId}`}>
                      {deltaText(qty as number, expected)}
                    </span>
                  ) : null}
                </div>
              );
            })}
          </div>
        )}
        <div className="bo-qcBar" data-ui="qc-bar">
          <div className="bo-qcBarInner" data-ui="qc-bar-inner">
            <Button
              variant="primary"
              disabled={touchedLines.length === 0}
              onClick={() => {
                setError("");
                setPhase("review");
              }}
              data-ui="qc-review"
              data-testid="qc-review"
            >
              Cerrar recuento ({touchedLines.length})
            </Button>
          </div>
        </div>
      </>
    );
  };

  const renderReview = () => {
    if (!sheet) return null;
    return (
      <>
        <div className="bo-qcCard" data-ui="qc-reviewcard">
          <h1 className="bo-qcTitle" data-ui="qc-review-title">Revisar recuento</h1>
          <p className="bo-qcMuted" data-ui="qc-review-sub">
            {sheet.warehouseName} · {touchedLines.length} líneas contadas. El stock quedará exactamente en estas cantidades.
          </p>
          <ul className="bo-qcReviewList" data-ui="qc-reviewlist">
            {touchedLines.map((line) => {
              const qty = parseQty(entries[line.itemId] ?? "") as number;
              const expected = expectedDisplay(line);
              return (
                <li className="bo-qcReviewRow" key={line.itemId} data-ui={`qc-review-row-${line.itemId}`}>
                  <span data-ui={`qc-review-name-${line.itemId}`}>{line.name}</span>
                  <span data-ui={`qc-review-value-${line.itemId}`}>
                    {fmtQty(qty)} {line.unitLabel}{" "}
                    <span className={`bo-qcDelta ${deltaClass(qty, expected)}`} data-ui={`qc-review-delta-${line.itemId}`}>
                      ({deltaText(qty, expected)})
                    </span>
                  </span>
                </li>
              );
            })}
          </ul>
          {error ? <InlineAlert kind="error" title={error} /> : null}
        </div>
        <div className="bo-qcBar" data-ui="qc-bar-review">
          <div className="bo-qcBarInner" data-ui="qc-bar-review-inner">
            <Button
              variant="ghost"
              disabled={closing}
              onClick={() => setPhase("count")}
              data-ui="qc-back"
              data-testid="qc-back"
            >
              Volver
            </Button>
            <Button
              variant="primary"
              disabled={closing || touchedLines.length === 0}
              onClick={() => void applyClose()}
              data-ui="qc-apply"
              data-testid="qc-apply"
            >
              {closing ? "Aplicando…" : "Aplicar recuento"}
            </Button>
          </div>
        </div>
      </>
    );
  };

  const renderDone = () => (
    <div className="bo-qcCard" data-ui="qc-done">
      <EmptyState
        icon={<ClipboardCheck size={32} aria-hidden="true" />}
        title="Recuento aplicado"
        description={
          applied
            ? `${applied.counted} líneas contadas · ${applied.changed} ajustes en ${applied.warehouseName}.`
            : "El stock se ha ajustado a lo contado."
        }
        data-ui="qc-done-state"
      />
      <div className="bo-qcDoneActions" data-ui="qc-done-actions">
        <Button variant="secondary" onClick={reset} data-ui="qc-new" data-testid="qc-new">
          Nuevo recuento
        </Button>
        <Button variant="ghost" onClick={() => navigate("/app/stock")} data-ui="qc-tostock" data-testid="qc-tostock">
          Volver al stock
        </Button>
      </div>
    </div>
  );

  return (
    <section className="bo-qc" aria-label="Recuento rápido de stock" data-ui="quick-count" data-testid="quick-count">
      {phase === "pick" ? renderPicker() : null}
      {phase === "count" ? renderCount() : null}
      {phase === "review" ? renderReview() : null}
      {phase === "done" ? renderDone() : null}
    </section>
  );
}
